### ISSUE TITLE
DOM manipulation

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/elm-web-api#6]
I've already implemented some APIs for listening to events on the `document` or `window` objects.

I've also got some work-in-progress that exposes methods for manipulating the DOM ... e.g. getting child nodes, creating nodes, adding nodes, etc.

At first, I thought that this would enable only some niche use cases -- things like adding elements to the header etc. -- that aren't possible via the usual elm-html architecture.

However, then I realized something. If we had access to the full set of DOM manipulation tools from Elm, then it would be possible to implement things like elm-html and virtual-dom in Elm itself. That is, things like elm-html and virtual-dom would no longer have to have any native code themselves -- they could be 'ported' to Elm rather than 'wrapped'.

The key benefit from that would be maintainability. That is, it would be easier to tweak elm-html and virtual-dom in Elm, rather than tweaking the javascript. Of course, there would also be a cost, in that the initial work in porting is greater than the initial work in wrapping. However, in some cases the flexibility and maintainability you gain will make it worthwhile.

Another way of stating this advantage is that when exposing basic Javascript APIs to Elm, there is a kind of 'correctness' that can be evaluated -- that is, one can reason about the nature of the Javascript API, how it ought to be exposed in Elm, and there is basically a right answer, and it can be tested. Packages like virtual-dom that wrap more complex Javascript are more open-ended. So, there are advantages to moving the complexity inside the Elm code, rather than leaving it in the Javascript.

This would also enable people to bypass some of the runtime magic for `main`, if they wish. In principle, `main` is basically a `Signal (Task () ())` -- it's just that there is a variety of different kinds of sugar which the runtime applies, depending on what type you actually give to `main`.

For instance, suppose you type `main` as `Signal Html`. It's not implemented this way, but conceptually the runtime maps that into a `Signal (Task () ())` in which the tasks efficiently update some part of the DOM to match the provided `Html`.

Now, if we exposed Tasks that can do all the low-level DOM manipulation, then the 'efficiently update some part of the DOM' part could actually be written in Elm itself. And, we could provide a method to explicitly map from the `Html` to the `Task` that performs the efficient update.

Then, you could start Elm up with `Elm.worker()`, and the tasks would update the DOM (rather than having the runtime magically do it). (And the equivalent of `Elm.fullscreen()` and `Elm.embed()` could actually be performed from within the Elm side of the code -- of course, it could be parameterized from the Javascript side via a port if needed for interop).

Now, all of this depends on (a) actually exposing the DOM manipulation APIs; and (b) porting elm-html and virtual-dom and parts of the runtime to pure Elm. So, it's a longish-term project. However, I don't think it requires any modifications to the runtime -- that is, I think what I've described can be implemented, given time and effort.

**Comment by vilterp** [comment]
This makes sense to me. Having an output port of rendering tasks in place of a special "main" feels like a nice simplification to me, but may seem weird to newcomers.

**Comment by rgrempel** [comment]
Closing, since I'm not expecting to do further work on this.
